### PR TITLE
fix all warnings

### LINKED ISSUE #17: fix all warnings

### PR DESCRIPTION
**Pull request by mila-laurel**
closes #17

### CODE REVIEW

File: CinemaCat.Application/Handlers/Images/UploadImage/UploadImageRequest.cs [hunk 1]
```diff
@@ -4,5 +4,5 @@ namespace CinemaCat.Application.Handlers.Images.UploadImage;
 
 public class UploadImageRequest : IRequest<UploadImageResponse>
 {
-    public Stream File { get; init; }
+    public Stream? File { get; init; }
```
Comment (rumkit) [inline CinemaCat.Application/Handlers/Images/UploadImage/UploadImageRequest.cs:7]: consider `required` non-nullable property

File: CinemaCat.Infrastructure/Extensions/ServiceCollectionExtensions.cs [hunk 2]
```diff
@@ -43,7 +43,7 @@ private static void AddBlobStorage(IServiceCollection serviceCollection, IConfig
     {
         serviceCollection.AddAzureClients(clientBuilder =>
         {
-            clientBuilder.AddBlobServiceClient(configuration.GetConnectionString("BlobStorage"), preferMsi: true);
+            clientBuilder.AddBlobServiceClient(configuration.GetConnectionString("BlobStorage") ?? string.Empty, preferMsi: true);
```
Comment (rumkit) [inline CinemaCat.Infrastructure/Extensions/ServiceCollectionExtensions.cs:46]: exception would be better here

File: CinemaCat.Application/Handlers/Images/UploadImage/UploadImageRequest.cs (hunk 1 above)
Comment (rumkit) [reply CinemaCat.Application/Handlers/Images/UploadImage/UploadImageRequest.cs:7]: also consider for other requests and responses

**Review by rumkit — CHANGES_REQUESTED** [review]

File: CinemaCat.Api/Program.cs [hunk 3]
```diff
@@ -53,7 +53,7 @@
     {
         ValidIssuer = builder.Configuration["Jwt:Issuer"],
         ValidAudience = builder.Configuration["Jwt:Audience"],
-        IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(builder.Configuration["Jwt:Key"] ?? string.Empty)),
+        IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(builder.Configuration["Jwt:Key"] ?? throw new ArgumentNullException("Jwt key"))),
```
Comment (rumkit) [inline CinemaCat.Api/Program.cs:56]: could be a custom exception, however, feel free to ignore the comment

**Review by rumkit — APPROVED** [review]
